[package]
name = "cpi_detee"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]  # Create a dynamic library

[dependencies]
lib_cpi = "0.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.8.1"
tempfile = "3.5.0"